apiVersion: secretmirror.example.com/v1alpha1
kind: SecretMirror
metadata:
  labels:
    app.kubernetes.io/name: cm-secret-mirror-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretmirror-sample
spec:
  # TODO(user): Add fields here
